import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/Navigation";
import AnimatedBackground from "@/components/AnimatedBackground";
import LanguageToggle from "@/components/LanguageToggle";
import { LanguageProvider } from "../../contexts/LanguageContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
       <AnimatedBackground />
       <LanguageProvider>
          <div className="min-h-screen bg-transparent">
            
              <Navigation />
              <LanguageToggle />            
                <main className="py-12 px-4 sm:px-6 lg:px-8">
                  <div className="max-w-3xl mx-auto">
                    {children}
                  </div>
                </main>
          </div>
        </LanguageProvider>
      </body>
    </html>
  );
}
